### PR TITLE
[DPE-2338] Use SCRAM

### PR DESCRIPTION
**Pull request by marceloneppel**
## Issue
PostgreSQL in this charm is using the not so secure MD5 password encryption.

## Solution
Remove this setting to use the default and more secure SCRAM-SHA-256 password encryption.

This PR reverts what was done on https://github.com/canonical/postgresql-k8s-operator/pull/52.

### CODE REVIEW

**Review by dragomirp — APPROVED** [review]

**Comment by dragomirp** [comment]
> This is absolutely great and long-waiting move! Q: are we safe for 'juju refresh' here? I am not sure about patroni reaction after the charm upgade. Can you please describe it before LGTM. Tnx!

AFAIK PG will keep on using the old hashes (md5) until they are regenerated by password change.

**Comment by marceloneppel** [comment]
> This is absolutely great and long-waiting move! Q: are we safe for 'juju refresh' here? I am not sure about patroni reaction after the charm upgade. Can you please describe it before LGTM. Tnx!

As Dragomir said it should keep working with legacy passwords. There is an issue that deletes users in an upgrade (because now in recent Juju versions a relation broken event is emitted), but should be fixed on https://github.com/canonical/postgresql-k8s-operator/pull/221.

**Review by taurus-forever — APPROVED** [review]
LGTM, the following regression expected:

deploy revision A (md5 pass), refresh revision B (SCRAM), rotate password, refresh revision A (rollback) => boom. Please document this in upgrade guide (section "Known rollback limitations").

**Comment by dragomirp** [comment]
> deploy revision A (md5 pass), refresh revision B (SCRAM), rotate password, refresh revision A (rollback) => boom. Please document this in upgrade guide (section "Known rollback limitations").

We need to test to make sure, but I don't think that's going to break. The change should affect how new password hashes are generated, it shouldn't break the ones that already exist. PG 14 should already support both.

**Comment by marceloneppel** [comment]
> LGTM, the following regression expected:
> 
> deploy revision A (md5 pass), refresh revision B (SCRAM), rotate password, refresh revision A (rollback) => boom. Please document this in upgrade guide (section "Known rollback limitations").

From a test locally, it worked fine (even after rotating the password, refreshing to the old revision - MD5 - and connecting again).

**Pull request merged**
