### PR TITLE
[DPE-4669] Test: Scale to zero units

### PR DESCRIPTION
**Pull request by BalabaDmitri**
**Issue** #508 

**Solution**
#### Test coverage of the following cases:
1. Scaling with and without storage.
2. Whether writes are increasing.
3. The shutdown of units after scale to zero.
4. Scaling up to 1 unit uses PVC with the other cluster's storage.
5. Remove the unit with another cluster's storage.
6. Restore own hostpath in PVC.
7. Scaling up to 1 and checking test data.
8. Scaling up to 3 and checking test data.

#### Implementation
1. Processing behaviour when using another cluster storage.

### CODE REVIEW

**Comment by lucasgameiroborges** [comment]
Hi @BalabaDmitri ! 
Could you please fix the linting issues so we can see the integration test running on CI? Thanks!

**Comment by lucasgameiroborges** [comment]
This PR seems stuck for a while, is it still under development? @BalabaDmitri

**Review by lucasgameiroborges — COMMENTED** [review]
Should we close this?

**Comment by marceloneppel** [comment]
> Should we close this?

Let's close it as it's stuck for a while.

**Pull request closed without merging**
