### PR TITLE
[DPE-2504] fully routable patroni cos

### PR DESCRIPTION
**Pull request by dragomirp**
## Issue
Cross model relation between COS Prometheus and Postgresql can't resolve the provided Patroni endpoint and it will not register new nodes.

## Solution
Switch to wildcard configuration.

### CODE REVIEW

**Comment by dragomirp** [comment]
Wildcard is using pod IPs which should be routable between modesl, however that likely means we won't be able to verify the certificate from Prometheus.

**Review by taurus-forever — APPROVED** [review]
Thank you for the quick fix!

**Comment by taurus-forever** [comment]
Q: why it is a problem with Patroni, and no such problem with PostgreSQL/PgBouncer? Are we exporting on Primary/Leader unit only for PgSQL/PgBouncer? Tnx!

**Comment by dragomirp** [comment]
> Q: why it is a problem with Patroni, and no such problem with PostgreSQL/PgBouncer? Are we exporting on Primary/Leader unit only for PgSQL/PgBouncer? Tnx!

Patroni API is its own exporter, but it's also potentially served over TLS. Everything else uses a dedicated exporter which serve plaintext. So Patroni was the only thing that used hostnames (for potential cert validation) instead of wildcard IP handled by the COS lib internally.

**Pull request merged**
