### PR TITLE
[MISC] Ignoring secret remove hook

### PR DESCRIPTION
**Pull request by dragomirp**
We don't really do any secrets related cleanup and handling this hook seems to cause a loop when using/removing TLS.

### CODE REVIEW

**Review by taurus-forever — APPROVED** [review]
@dragomirp mentioned issues here on a sycn. I am fine to merge this AFTER the next stable release. Sure, feel free to merge if stable. Tnx for cleanup!

**Review by lucasgameiroborges — APPROVED** [review]
Nice, thanks!!

**Review by marceloneppel — APPROVED** [review]
LGTM!

**Comment by dragomirp** [comment]
Superseded by https://github.com/canonical/postgresql-k8s-operator/pull/484

**Pull request closed without merging**
